# Generated by Django 3.2.16 on 2022-12-04 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_workshop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='booked_dates',
            field=models.ManyToManyField(blank=True, related_name='booked_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='email',
            field=models.EmailField(default='E-mail address', max_length=254),
        ),
    ]
