# Generated by Django 3.2.16 on 2022-12-04 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_auto_20221204_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='booked_dates',
        ),
        migrations.AddField(
            model_name='workshop',
            name='booked_dates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_dates', to=settings.AUTH_USER_MODEL),
        ),
    ]
