# Generated by Django 3.2.16 on 2022-12-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_workshop_booked_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='booked_dates',
        ),
    ]
