# Generated by Django 3.2.16 on 2022-11-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221124_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unassignable'), (1, 'European'), (2, 'Asian'), (3, 'Arabic'), (4, 'African'), (5, 'North-/Southamerican')], default=0),
        ),
    ]
